export const PROPERTY_TYPE = ['House', 'Appartment', 'Room']

export const MIN_PRICE = [0, 200000, 500000, 1000000] // Economy, Mid-Range, High-End
export const MAX_PRICE = [500000, 1000000, 0] // Economy, Mid-Range, High-End

export const PROVINCES = [
  'Seoul (서울)',
  'Busan (부산)',
  'Daegu (대구)',
  'Incheon (인천)',
  'Gwangju (광주)',
  'Daejeon (대전)',
  'Ulsan (울산)',
  'Gyeonggi (경기)',
  'Gangwon (강원도)',
  'Chungcheongbuk (충청북도)',
  'Chungcheongnam (충청남도)',
  'Jeollabuk (전라북도)',
  'Jeollanam (전라남도)',
  'Gyeongsangbuk (경상북도)',
  'Gyeongsangnam (경상남도)',
  'Jeju (제주)',
]

export enum Amenities {
  FURNISHED_KITCHEN = 'Furnished Kitchen (가구가 구비된 주방)',
  COMMON_AREA = 'Common Area (공용 공간)',
  SOFA = 'Sofa (소파)',
  STORAGE_SPACE = 'Storage Space (저장 공간)',
  MICROWAVE = 'Microwave (마이크로파)',
  AIR_CONDITIONER = 'Air Conditioner (에어컨)',
  TV = 'TV (텔레비전)',
  LAUNDRY_ROOM = 'Laundry Room (세탁실)',
  STUDY_AREA = 'Study Area (학습 영역)',
  HIGH_SPEED_INTERNET = 'High-speed Internet/Wi-Fi (초고속 인터넷/와이파이)',
  GYM = 'Gym/Fitness Center (체육관/피트니스 센터)',
  SWIMMING_POOL = 'Swimming Pool (수영장)',
  PARKING_SPACE = 'Parking Space (주차 공간)',
  SECURITY = '24/7 Security (연중무휴 보안)',
  ROOFTOP_TERRACE = 'Rooftop Terrace (루프탑 테라스)',
  GAME_ROOM = 'Game Room (게임방)',
  BICYCLE_STORAGE = 'Bicycle Storage (자전거 보관소)',
  MAINTENANCE = 'On-site Maintenance (현장 유지보수)',
  PRINTING_FACILITIES = 'Printing/Scanning Facilities (인쇄/스캔 시설)',
  SOCIAL_EVENTS_AREA = 'Social Events/Activities Area (사교 행사/활동 공간)',

  // Room Amenities
  BED_WITH_MATTRESS = 'Bed with Mattress (매트리스가 있는 침대)',
  DESK_AND_CHAIR = 'Desk and Chair (책상과 의자)',
  WARDROBE = 'Wardrobe/Closet (옷장/옷장)',
  BOOKSHELF = 'Bookshelf (책장)',
  BEDSIDE_TABLE = 'Bedside Table (침대 옆 탁자)',
  LAMP = 'Lamp/Lighting (램프/조명)',
  MIRROR = 'Mirror (거울)',
  MINI_FRIDGE = 'Mini-fridge (미니 냉장고)',
  EN_SUITE_BATHROOM = 'En-suite Bathroom (실내 욕실)',
  STUDY_LAMP = 'Study Lamp (연구 램프)',
  BLACKOUT_CURTAINS = 'Blackout Curtains (암막 커튼)',
  ROOM_CLEANING_SERVICE = 'Room Cleaning Service (객실 청소 서비스)',
  BEDDING_AND_LINENS = 'Bedding and Linens (침구 및 린넨)',
  SHARED_BATHROOM = 'Shared Bathroom Facilities (공용 욕실 시설)',
  LOCKABLE_STORAGE = 'Lockable Storage (잠글 수 있는 보관함)',

  // House Amenities
  FURNISHED_LIVING_ROOM = 'Furnished Living Room (가구가 딸린 거실)',
  DINING_AREA = 'Dining Area (식사 공간)',
  BACKYARD = 'Backyard/Garden (뒤뜰/정원)',
  BARBECUE_AREA = 'Barbecue Area (뒤뜰/정원)',
  GARAGE_OR_PARKING = 'Garage or Parking Area (차고 또는 주차 공간)',
  HOUSEKEEPING = 'Housekeeping Services (하우스키핑 서비스)',
  PET_FRIENDLY_FACILITIES = 'Pet-friendly Facilities (반려동물 친화적인 시설)',
  OUTDOOR_SEATING = 'Outdoor Seating/Patio (야외 좌석/파티오)',
  FIREPLACE = 'Fireplace (난로)',
  RECYCLING_FACILITIES = 'Recycling Facilities (재활용 시설)',
  LANDSCAPING = 'Landscaping/Green Spaces (조경/녹지 공간)',
  SECURITY_CAMERAS = 'Security Cameras/Alarms (보안 카메라/경보)',
  BULLETIN_BOARD = 'Community Bulletin Board (커뮤니티 게시판)',
  OUTDOOR_SPORTS_FACILITIES = 'Outdoor Sports Facilities (Basketball hoop, volleyball net, etc.) (야외체육시설(농구후프, 배구네트 등))',
}
