export const AccomodationProperties = [
  {
    propertyName: 'Cozy Apartment',
    location: 'Downtown',
    pricePerMonth: 1200,
    deposit: 1500,
    status: 'Pending',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Modern Loft',
    location: 'City Center',
    pricePerMonth: 1800,
    deposit: 2000,
    status: 'Approved',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Family Home',
    location: 'Suburbs',
    pricePerMonth: 2500,
    deposit: 3000,
    status: 'Rejected',
    actions: ['Contact Landlord'],
  },
  {
    propertyName: 'Studio Apartment',
    location: 'Midtown',
    pricePerMonth: 900,
    deposit: 1200,
    status: 'Waiting',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Lakefront Cottage',
    location: 'Outskirts',
    pricePerMonth: 1500,
    deposit: 1800,
    status: 'Pending',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Luxury Condo',
    location: 'Waterfront',
    pricePerMonth: 3500,
    deposit: 4000,
    status: 'Approved',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Townhouse',
    location: 'Historic District',
    pricePerMonth: 2800,
    deposit: 3200,
    status: 'Pending',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Rustic Cabin',
    location: 'Mountain Range',
    pricePerMonth: 1200,
    deposit: 1500,
    status: 'Waiting',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Garden Villa',
    location: 'Countryside',
    pricePerMonth: 2000,
    deposit: 2500,
    status: 'Pending',
    actions: ['View Details', 'Contact Agent'],
  },
  {
    propertyName: 'Penthouse Suite',
    location: 'Skyline',
    pricePerMonth: 5000,
    deposit: 6000,
    status: 'Approved',
    actions: ['View Details', 'Contact Agent'],
  },
]
