export const blogs = [
  {
    ID: 1,
    Title: 'Understanding JavaScript Closures',
    Author: 'JohnDoe',
    Category: 'Programming',
    Tags: ['JavaScript', 'Closures', 'Coding'],
    DateCreated: '2024-01-01T10:00:00Z',
    DatePublished: '2024-01-02T12:00:00Z',
    Status: 'Published',
    Views: 250,
    Comments: 12,
    Likes: 30,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 2,
    Title: '10 Best Travel Destinations for 2024',
    Author: 'JaneSmith',
    Category: 'Travel',
    Tags: ['Travel', 'Destinations', 'Tips'],
    DateCreated: '2024-01-05T08:30:00Z',
    DatePublished: '2024-01-06T09:00:00Z',
    Status: 'Published',
    Views: 500,
    Comments: 20,
    Likes: 50,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 3,
    Title: 'Healthy Eating on a Budget',
    Author: 'AliceW',
    Category: 'Health',
    Tags: ['Health', 'Nutrition', 'Budget'],
    DateCreated: '2024-02-10T11:00:00Z',
    DatePublished: '2024-02-11T15:00:00Z',
    Status: 'Published',
    Views: 300,
    Comments: 15,
    Likes: 40,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 4,
    Title: 'Mastering CSS Grid Layout',
    Author: 'BobK',
    Category: 'Web Development',
    Tags: ['CSS', 'Grid', 'Web Design'],
    DateCreated: '2024-03-01T14:00:00Z',
    DatePublished: '2024-03-02T16:00:00Z',
    Status: 'Published',
    Views: 450,
    Comments: 25,
    Likes: 60,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 5,
    Title: "Investing 101: A Beginner's Guide",
    Author: 'CarolL',
    Category: 'Finance',
    Tags: ['Investing', 'Finance', 'Beginners'],
    DateCreated: '2024-03-15T09:00:00Z',
    DatePublished: '2024-03-16T10:00:00Z',
    Status: 'Published',
    Views: 600,
    Comments: 30,
    Likes: 70,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 6,
    Title: 'Meditation Techniques for Beginners',
    Author: 'DaveM',
    Category: 'Lifestyle',
    Tags: ['Meditation', 'Mindfulness', 'Beginners'],
    DateCreated: '2024-04-05T07:00:00Z',
    DatePublished: '2024-04-06T08:00:00Z',
    Status: 'Published',
    Views: 200,
    Comments: 10,
    Likes: 25,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 7,
    Title: 'Top 5 Programming Languages to Learn in 2024',
    Author: 'EmilyR',
    Category: 'Programming',
    Tags: ['Programming', 'Languages', '2024'],
    DateCreated: '2024-04-15T13:00:00Z',
    DatePublished: '2024-04-16T14:00:00Z',
    Status: 'Published',
    Views: 800,
    Comments: 35,
    Likes: 90,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 8,
    Title: 'The Benefits of Yoga for Mental Health',
    Author: 'FionaG',
    Category: 'Health',
    Tags: ['Yoga', 'Mental Health', 'Wellness'],
    DateCreated: '2024-05-01T12:00:00Z',
    DatePublished: '2024-05-02T13:00:00Z',
    Status: 'Published',
    Views: 350,
    Comments: 18,
    Likes: 45,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 9,
    Title: 'Building Your First Mobile App',
    Author: 'GeorgeP',
    Category: 'Mobile Development',
    Tags: ['Mobile', 'App Development', 'Beginners'],
    DateCreated: '2024-05-10T15:00:00Z',
    DatePublished: '2024-05-11T16:00:00Z',
    Status: 'Published',
    Views: 400,
    Comments: 22,
    Likes: 55,
    Actions: ['Edit', 'Delete'],
  },
  {
    ID: 10,
    Title: 'Exploring the World of Artificial Intelligence',
    Author: 'HannahT',
    Category: 'Technology',
    Tags: ['AI', 'Technology', 'Innovation'],
    DateCreated: '2024-06-01T11:00:00Z',
    DatePublished: '2024-06-02T12:00:00Z',
    Status: 'Published',
    Views: 750,
    Comments: 40,
    Likes: 85,
    Actions: ['Edit', 'Delete'],
  },
]

export const Categoryoptions = [
  {
    value: 'programming',
    label: 'Programming',
  },
  {
    value: 'health',
    label: 'Health',
  },
  {
    value: 'travel',
    label: 'Travel',
  },
  {
    value: 'finance',
    label: 'Finance',
  },
  {
    value: 'lifestyle',
    label: 'Lifestyle',
  },
  {
    value: 'webDevelopment',
    label: 'Web Development',
  },
  {
    value: 'mobileDevelopment',
    label: 'Mobile Development',
  },
  {
    value: 'technology',
    label: 'Technology',
  },
  {
    value: 'education',
    label: 'Education',
  },
  {
    value: 'food',
    label: 'Food',
  },
]

export const TagsOption = [
  {
    value: 'javascript',
    label: 'JavaScript',
  },
  {
    value: 'fitness',
    label: 'Fitness',
  },
  {
    value: 'vacation',
    label: 'Vacation',
  },
  {
    value: 'investment',
    label: 'Investment',
  },
  {
    value: 'mindfulness',
    label: 'Mindfulness',
  },
  {
    value: 'css',
    label: 'CSS',
  },
  {
    value: 'ios',
    label: 'iOS',
  },
  {
    value: 'ai',
    label: 'Artificial Intelligence',
  },
  {
    value: 'onlineLearning',
    label: 'Online Learning',
  },
  {
    value: 'recipes',
    label: 'Recipes',
  },
]
