export const coursesList = [
  {
    courseId: 1,
    courseName: 'Introduction to Computer Science',
    courseCode: 'CS101',
    department: 'Computer Science',
    instructor: 'John Doe',
    description:
      'An introductory course covering fundamental concepts of computer science.',
    creditHours: 3,
    startDate: '2024-09-01',
    endDate: '2024-12-15',
    schedule: 'MWF 10:00 AM',
    location: 'Smith Hall',
    capacity: 50,
    currentEnrollment: 45,
    prerequisites: 'None',
    status: 'Active',
  },
  {
    courseId: 2,
    courseName: 'Calculus I',
    courseCode: 'MATH101',
    department: 'Mathematics',
    instructor: 'Jane Smith',
    description:
      'A foundational course in calculus for science and engineering majors.',
    creditHours: 4,
    startDate: '2024-09-05',
    endDate: '2024-12-18',
    schedule: 'TTh 1:00 PM',
    location: 'Brown Hall',
    capacity: 40,
    currentEnrollment: 38,
    prerequisites: 'High school algebra',
    status: 'Active',
  },
  {
    courseId: 3,
    courseName: 'Physics Fundamentals',
    courseCode: 'PHYS101',
    department: 'Physics',
    instructor: 'Michael Johnson',
    description: 'An introductory course covering basic principles of physics.',
    creditHours: 4,
    startDate: '2024-09-03',
    endDate: '2024-12-17',
    schedule: 'MW 9:30 AM',
    location: 'Science Building',
    capacity: 35,
    currentEnrollment: 32,
    prerequisites: 'High school physics',
    status: 'Active',
  },
  // Add more courses here...
  {
    courseId: 4,
    courseName: 'Introduction to Psychology',
    courseCode: 'PSYC101',
    department: 'Psychology',
    instructor: 'Sarah Johnson',
    description:
      'An introductory course covering basic concepts in psychology.',
    creditHours: 3,
    startDate: '2024-09-02',
    endDate: '2024-12-16',
    schedule: 'MWF 1:00 PM',
    location: 'Psychology Building',
    capacity: 40,
    currentEnrollment: 36,
    prerequisites: 'None',
    status: 'Active',
  },
  {
    courseId: 5,
    courseName: 'English Composition',
    courseCode: 'ENGL101',
    department: 'English',
    instructor: 'Emily Brown',
    description:
      'A writing-intensive course focusing on English composition skills.',
    creditHours: 3,
    startDate: '2024-09-04',
    endDate: '2024-12-14',
    schedule: 'TTh 9:00 AM',
    location: 'Humanities Building',
    capacity: 30,
    currentEnrollment: 28,
    prerequisites: 'None',
    status: 'Active',
  },
  {
    courseId: 1,
    courseName: 'Introduction to Computer Science',
    courseCode: 'CS101',
    department: 'Computer Science',
    instructor: 'John Doe',
    description:
      'An introductory course covering fundamental concepts of computer science.',
    creditHours: 3,
    startDate: '2024-09-01',
    endDate: '2024-12-15',
    schedule: 'MWF 10:00 AM',
    location: 'Smith Hall',
    capacity: 50,
    currentEnrollment: 45,
    prerequisites: 'None',
    status: 'Active',
  },
  {
    courseId: 2,
    courseName: 'Calculus I',
    courseCode: 'MATH101',
    department: 'Mathematics',
    instructor: 'Jane Smith',
    description:
      'A foundational course in calculus for science and engineering majors.',
    creditHours: 4,
    startDate: '2024-09-05',
    endDate: '2024-12-18',
    schedule: 'TTh 1:00 PM',
    location: 'Brown Hall',
    capacity: 40,
    currentEnrollment: 38,
    prerequisites: 'High school algebra',
    status: 'Active',
  },
  {
    courseId: 3,
    courseName: 'Physics Fundamentals',
    courseCode: 'PHYS101',
    department: 'Physics',
    instructor: 'Michael Johnson',
    description: 'An introductory course covering basic principles of physics.',
    creditHours: 4,
    startDate: '2024-09-03',
    endDate: '2024-12-17',
    schedule: 'MW 9:30 AM',
    location: 'Science Building',
    capacity: 35,
    currentEnrollment: 32,
    prerequisites: 'High school physics',
    status: 'Active',
  },
  // Add more courses here...
  {
    courseId: 4,
    courseName: 'Introduction to Psychology',
    courseCode: 'PSYC101',
    department: 'Psychology',
    instructor: 'Sarah Johnson',
    description:
      'An introductory course covering basic concepts in psychology.',
    creditHours: 3,
    startDate: '2024-09-02',
    endDate: '2024-12-16',
    schedule: 'MWF 1:00 PM',
    location: 'Psychology Building',
    capacity: 40,
    currentEnrollment: 36,
    prerequisites: 'None',
    status: 'Active',
  },
  {
    courseId: 5,
    courseName: 'English Composition',
    courseCode: 'ENGL101',
    department: 'English',
    instructor: 'Emily Brown',
    description:
      'A writing-intensive course focusing on English composition skills.',
    creditHours: 3,
    startDate: '2024-09-04',
    endDate: '2024-12-14',
    schedule: 'TTh 9:00 AM',
    location: 'Humanities Building',
    capacity: 30,
    currentEnrollment: 28,
    prerequisites: 'None',
    status: 'Active',
  },
]
